<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>archlinux on 111qqz的小窝</title><link>https://111qqz.com/tags/archlinux/</link><description>Recent content in archlinux on 111qqz的小窝</description><generator>Hugo -- gohugo.io</generator><language>en</language><copyright>Copyright © 2012-2022 all rights reserved.</copyright><lastBuildDate>Wed, 11 Oct 2017 16:24:11 +0000</lastBuildDate><atom:link href="https://111qqz.com/tags/archlinux/index.xml" rel="self" type="application/rss+xml"/><item><title>archlinux/manjaro fcitx 与 chrome 不兼容 中文掉字 解决办法</title><link>https://111qqz.com/2017/10/manjaro-fcitx-drop-chinese-words-randomly/</link><pubDate>Wed, 11 Oct 2017 16:24:11 +0000</pubDate><guid>https://111qqz.com/2017/10/manjaro-fcitx-drop-chinese-words-randomly/</guid><description>
[已解决]最近两个版本的 chrome（aura界面）有两个问题
https://github.com/fcitx/fcitx/issues/197
解决办法： 安装fcitx-im 包即可</description></item><item><title>manjaro(archlinux) 安装 YouCompleteMe</title><link>https://111qqz.com/2017/07/install-YouCompleteMe-on-manjaro/</link><pubDate>Fri, 28 Jul 2017 09:13:34 +0000</pubDate><guid>https://111qqz.com/2017/07/install-YouCompleteMe-on-manjaro/</guid><description>
来来回回折腾了好多次，aur直接安装或者手动编译，安装后都无法补全
ycm的log文件是在/tmp目录下的。
发现问题是缺少libtinfo.so.5
2017-07-28 17:02:12,667 - ERROR - Error occurred while loading global extra conf /home/coder/.ycm_extra_conf.py Traceback (most recent call last): File &amp;quot;/home/coder/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/extra_conf_store.py&amp;quot;, line 94, in _CallGlobalExtraConfMethod module = Load( global_ycm_extra_conf, force = True ) File &amp;quot;/home/coder/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/extra_conf_store.py&amp;quot;, line 173, in Load module = LoadPythonSource( _RandomName(), module_file ) File &amp;quot;/home/coder/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/utils.py&amp;quot;, line 400, in LoadPythonSource return imp.load_source( name, pathname ) File &amp;quot;/home/coder/.ycm_extra_conf.py&amp;quot;, line 32, in &amp;lt;module&amp;gt; import ycm_core ImportError: libtinfo.so.5: cannot open shared object file: No such file or directory 2017-07-28 17:02:12,667 - ERROR - libtinfo.</description></item></channel></rss>